# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
