# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
