# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171211_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
