# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feedback_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u043d\u0435\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.TextField(max_length=100, verbose_name='\u0422\u0435\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.CharField(max_length=150, verbose_name='\u0410\u043b\u0438\u0430\u0441'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(max_length=250, verbose_name='\u041c\u0435\u0442\u0430-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(max_length=250, verbose_name='\u041c\u0435\u0442\u0430-\u0441\u043b\u043e\u0432\u043e\u0441\u043e\u0447\u0438\u0442\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(max_length=150, verbose_name='\u041c\u0435\u0442\u0430-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=150, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
