# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_auto_20171205_1442'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('new_category', models.TextField()),
                ('new_bu', models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], max_length=10)),
                ('opt_roznica', models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], max_length=10)),
                ('price', models.FloatField()),
                ('ammount', models.IntegerField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('created_at', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
