# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_subsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('new_category', models.TextField()),
                ('new_bu', models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], max_length=10)),
                ('opt_roznica', models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], max_length=10)),
                ('price', models.FloatField()),
                ('ammount', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='new_announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('cropping', image_cropping.fields.ImageRatioField('photo', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
