# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newannouncement',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='newannouncement',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='newannouncement',
            old_name='user_id',
            new_name='user',
        ),
    ]
