# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='once',
            field=models.CharField(choices=[('once', '\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f \u043f\u043e\u043a\u0443\u043f\u043a\u0430'), ('regular', '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f')], default='once', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('service', '\u0423\u0441\u043b\u0443\u0433\u0430'), ('good', '\u0422\u043e\u0432\u0430\u0440')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='once',
            field=models.CharField(choices=[('once', '\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f \u043f\u043e\u043a\u0443\u043f\u043a\u0430'), ('regular', '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f')], default='once', max_length=10),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='type',
            field=models.CharField(choices=[('service', '\u0423\u0441\u043b\u0443\u0433\u0430'), ('good', '\u0422\u043e\u0432\u0430\u0440')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='new_bu',
            field=models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='opt_roznica',
            field=models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default='retail', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='new_bu',
            field=models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='opt_roznica',
            field=models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default='retail', max_length=10),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
