# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_subsubcategory'),
        ('archive', '0002_auto_20171211_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='sub_sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='sub_sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
    ]
