# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20171209_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newannouncement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='new_announcements/'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
