# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20171211_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Date expire'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_paid_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Date paid expire'),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='date_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Date expire'),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='date_paid_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Date paid expire'),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
