# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20171209_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
