# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_subsubcategory'),
        ('archive', '0004_auto_20171211_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region'),
            preserve_default=False,
        ),
    ]
