# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:14
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20171209_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='newannouncement',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
