# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20171213_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='new_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='new_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
