# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20171213_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory'),
        ),
    ]
