# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20171213_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
    ]
