# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20171213_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='new_city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='new_city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region'),
        ),
    ]
