# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0011_auto_20171214_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermessage',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
            preserve_default=False,
        ),
    ]
