# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20171214_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive.Announcement', verbose_name='\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ammount',
            field=models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041a\u0430\u0434\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_expire',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_paid_expire',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0435\u043c\u043e\u0435'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='new_bu',
            field=models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], default='new', max_length=10, verbose_name='\u041d\u043e\u0432\u043e\u0435/\u0411\u0423'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='new_category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u043e\u0432\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='new_city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u043e\u0432\u044b\u0439 \u0433\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='once',
            field=models.CharField(choices=[('once', '\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f \u043f\u043e\u043a\u0443\u043f\u043a\u0430'), ('regular', '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f')], default='once', max_length=10, verbose_name='\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f/\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='opt_roznica',
            field=models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default='retail', max_length=10, verbose_name='\u041e\u043f\u0442/\u0420\u043e\u0437\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory', verbose_name='\u041f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory', verbose_name='\u041f\u043e\u0434 \u043f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('service', '\u0423\u0441\u043b\u0443\u0433\u0430'), ('good', '\u0422\u043e\u0432\u0430\u0440')], default='good', max_length=10, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='ammount',
            field=models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041a\u0430\u0434\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='date_expire',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='date_paid_expire',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0435\u043c\u043e\u0435'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='new_bu',
            field=models.CharField(choices=[('new', '\u041d\u043e\u0432\u043e\u0435'), ('used', '\u0411\u0423')], default='new', max_length=10, verbose_name='\u041d\u043e\u0432\u043e\u0435/\u0411\u0423'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='new_category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u043e\u0432\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='new_city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041d\u043e\u0432\u044b\u0439 \u0433\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='once',
            field=models.CharField(choices=[('once', '\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f \u043f\u043e\u043a\u0443\u043f\u043a\u0430'), ('regular', '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f')], default='once', max_length=10, verbose_name='\u041e\u0434\u043d\u043e\u0440\u0430\u0437\u043e\u0432\u0430\u044f/\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='opt_roznica',
            field=models.CharField(choices=[('opt', '\u041e\u043f\u0442'), ('retail', '\u0420\u043e\u0437\u043d\u0438\u0446\u0430')], default='retail', max_length=10, verbose_name='\u041e\u043f\u0442/\u0420\u043e\u0437\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory', verbose_name='\u041f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubSubCategory', verbose_name='\u041f\u043e\u0434 \u043f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='title',
            field=models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='type',
            field=models.CharField(choices=[('service', '\u0423\u0441\u043b\u0443\u0433\u0430'), ('good', '\u0422\u043e\u0432\u0430\u0440')], default='good', max_length=10, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
