# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20171214_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
