# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20171220_1240'),
        ('archive', '0012_auto_20171215_1224'),
    ]

    operations = [
    ]
