# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_merge_20171220_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='newannouncement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
