# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20171220_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermessage',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
