# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20171222_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermessage',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='\u041d\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
    ]
