# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20171222_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='current_offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0443\u0449\u0435\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='current_offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0443\u0449\u0435\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
