# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_auto_20180110_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043d\u0430\u044f \u0441\u0434\u0435\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='newannouncement',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043d\u0430\u044f \u0441\u0434\u0435\u043b\u043a\u0430'),
        ),
    ]
