# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_slug',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
