# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171205_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_slug', models.CharField(max_length=150)),
                ('parent_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory')),
            ],
        ),
    ]
