# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_subsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '255x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_pic/'),
        ),
    ]
