# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replanishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 8, 3, 17, 222413, tzinfo=utc))),
                ('system', models.CharField(max_length=150)),
                ('user_replanishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
