# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replanishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 7, 14, 27, 536304, tzinfo=utc))),
                ('system', models.CharField(max_length=150)),
                ('user_replanishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]