# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replanishment',
            name='system',
        ),
        migrations.AddField(
            model_name='replanishment',
            name='Replanishment_system',
            field=models.CharField(choices=[(('VS',), 'Visa'), (('MC',), 'MasterCard'), (('WM',), 'WebMoney')], default=('MC',), max_length=150),
        ),
        migrations.AlterField(
            model_name='replanishment',
            name='ammount',
            field=models.FloatField(verbose_name='\u0441\u0443\u043c\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='replanishment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 9, 53, 16, 722743, tzinfo=utc)),
        ),
    ]
