# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replanishment',
            name='ammount',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0441\u0443\u043c\u043c\u0430'),
        ),
    ]
