# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0003_auto_20171208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replanishment',
            name='Replanishment_system',
            field=models.CharField(choices=[('VS', 'Visa'), ('MC', 'MasterCard'), ('WM', 'WebMoney')], default='VS', max_length=150, verbose_name='\u043f\u043b\u0430\u0442\u0435\u0436\u043d\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430'),
        ),
    ]
