# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0004_auto_20171211_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replanishment',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='replanishment',
            name='Replanishment_system',
        ),
        migrations.AddField(
            model_name='replanishment',
            name='status',
            field=models.CharField(choices=[('pending', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435 '), ('approved', '\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'), ('declined', '\u043e\u0442\u043a\u043b\u043e\u043d\u0435\u043d')], default='pending', max_length=100, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
