# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0005_auto_20171215_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replanishment',
            name='user_replanishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
